[package]
name = "pundoc"
version = "0.1.0"
authors = ["oberien <jaro.fietz@gmx.de>"]

[dependencies]
pulldown-cmark = "0.1.2"
str-concat = "0.1.4"
structopt = "0.2.10"
void = "1.0.2"
boolinator = "2.4"
